//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sciendo.Fitas.Containers.MD
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int dialog_LabelField = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int dialog_ValueField = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int facebook = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int history = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int map_view = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int start = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int start_activity = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int view1 = 2131099650;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_labelfieldright = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Splash = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int menu_activity = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int menu_activity_done = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int menu_day_done = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int menu_day_not_done = 2131034115;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int FacebookMessage = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
